openapi: 3.0.1
info:
  title: ChainingAPI
  description: API Definition of ChainingAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/chain
- url: https://localhost:8253/chain
paths:
  /:
    get:
      responses:
        default:
          description: Default response
