openapi: 3.0.1
info:
  title: EmailTestAPI
  description: API Definition of EmailTestAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/emailtestapi
- url: https://localhost:8253/emailtestapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
