openapi: 3.0.1
info:
  title: GreetingAPI
  description: API Definition of GreetingAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/greet
- url: https://localhost:8253/greet
paths:
  /:
    get:
      responses:
        default:
          description: Default response
  /{name}:
    get:
      parameters:
      - name: name
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
