openapi: 3.0.1
info:
  title: StoreAPI
  description: API Definition of StoreAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/store
- url: https://localhost:8253/store
paths:
  /:
    get:
      responses:
        default:
          description: Default response
