openapi: 3.0.1
info:
  title: TransformAPI
  description: API Definition of TransformAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/transform
- url: https://localhost:8253/transform
paths:
  /:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
